export const ACTIONS = {
  SET_FILTER_NAME: "SET_FILTER_NAME",
  SET_APP: "SET_APP",
  SET_REQUESTS: "SET_REQUESTS",
  SET_RESPONSES: "SET_RESPONSES",
  SET_IMPRESSIONS: "SET_IMPRESSIONS",
  SET_CLICKS: "SET_CLICKS",
  SET_REVENUE: "SET_REVENUE",
};
